blank_issues_enabled: false
contact_links:
  - name: OpenDesk Support System Documentation
    url: https://github.com/siddjoshi/opendesk-support-system/wiki
    about: Please check the documentation before creating an issue
  - name: Ask a Question
    url: https://github.com/siddjoshi/opendesk-support-system/discussions
    about: Ask questions and discuss ideas in GitHub Discussions